# docker run -d --rm --name mongo -p 27017:27017 -v mongodbdata:/data/db mongo
# docker run -d --rm --name store-mongo -p 27017:27017 -v mongo-db-persistance-store:/data/db -v mongo-db-config-store:/data/configdb mongo

version: "3.8"

services:
  mongo:
    image: mongo
    container_name: store-mongo
    ports:
      - 27017:27017
    volumes:
      - mongo-db-persistance-store:/data/db
      - mongo-db-config-store:/data/configdb

volumes:
  mongo-db-persistance-store:
  mongo-db-config-store:
